# 请选择清理类型 normal 和 wait 见下面
clearType: normal
# 启用清理的世界
world:
  - world
  - plotworld
  - DIM72
  - DIM1
  - DIM-1
# 不清理的精灵图鉴id
# 这里的 132 是 百变怪的
# 请打开 客户端 按 I 打开图鉴
# 在图鉴中 精灵名字后面 # 后面的数字就是图鉴ID
# 必须使用这个图鉴ID 请勿使用百度和其他网站的ID
unClearDexID:
  - 132

# 清理类型 : normal
normal:
  # 每隔多长时间清理一次精灵
  time: 130
  # 是否清理神兽
  le: false
  # 是否清理异兽
  ul: false
  # 是否清理闪光
  shiny: true
  # 是否清理 boss
  boss: true
  # 是否清理非自然生成的精灵 例如 /pokespawn 和 幸运方块生成的精灵
  canDeSpawn: true
  # 倒计时提示类型 PLAYER(只发送给玩家) CONSOLE(只发给后台) ALL(玩家和后台都发)
  message-type: ALL
  # 这里的 倒计时可以自己添加任意的时间 仿照下面的格式 加入第几秒的时候倒计时就可以了 必须是整数开头然后 冒号
  message:
    120: "&7[&c!&7] &f世界中普通野生精灵将在 120 秒后被强制清场"
    60: "&7[&c!&7] &f世界中普通野生精灵将在 60 秒后被强制清场"
    30: "&7[&c!&7] &f世界中普通野生精灵将在 30 秒后被强制清场"
    10: "&7[&c!&7] &f世界中普通野生精灵将在 10 秒后被强制清场"
    5: "&7[&c!&7] &f世界中普通野生精灵将在 5 秒后被强制清场"
    0: "&7[&c!&7] &f世界中普通野生精灵已被清理 %num% 只"
# 清理类型： wait
# 将最上面的 clearType 改成 wait 启用 等待式清理
wait:
  clear:
    # 是否清理神兽
    le: false
    # 是否清理异兽
    ul: false
    # 是否清理闪光
    shiny: true
    # 是否清理 boss
    boss: true
    # 是否清理非自然生成的精灵 例如 /pokespawn 和 幸运方块生成的精灵
    canDeSpawn: true
  time:
    # 每隔多少秒清理一次精灵
    cycle: 500
    # 一只精灵被生成以后 多少秒 以后才可以被清理
    # 就相当于 让这个精灵在这个世界上呆够多少秒以后才可以被清理插件清理掉
    wait: 800
  # 倒计时提示类型 PLAYER(只发送给玩家) CONSOLE(只发给后台) ALL(玩家和后台都发)
  message-type: ALL
    # 这里的 倒计时可以自己添加任意的时间 仿照下面的格式 加入第几秒的时候倒计时就可以了 必须是整数开头然后 冒号
  message:
    120: "&7[&c!&7] &f世界中冗余普通野生精灵将在 120 秒后被强制清场"
    60: "&7[&c!&7] &f世界中冗余普通野生精灵将在 60 秒后被强制清场"
    30: "&7[&c!&7] &f世界中冗余普通野生精灵将在 30 秒后被强制清场"
    10: "&7[&c!&7] &f世界中冗余普通野生精灵将在 10 秒后被强制清场"
    5: "&7[&c!&7] &f世界中冗余普通野生精灵将在 5 秒后被强制清场"
    0: "&7[&c!&7] &f冗余野生精灵已被清退 %num%只,有 %wait%只 冗余精灵将在被下次强制清场"
